package faker.generator;

public enum FakeInternetType {
    EMAIL, DOMAIN_NAME, DOMAIN_WORD, DOMAIN_SUFFIX, URL, AVATAR, IMAGE, PASSWORD, MAC_ADDRESS,
    IPV4, PRIVATE_IPV4, PUBLIC_IPV4, IPV4_CIDR, IPV6, IPV6_CIDR, SLUG, UUID
}
